### ISSUE TITLE
Issues with new Date() in ngDate

### ISSUE THREAD

**Issue by of6** [jfmdev/ngComboDatePicker#3]
So there seems to be a bug with how new Date() is interpreted. If you only put the year-mo-day it shows one day older in the select drop downs, even though the stored value is correct. This shows up in your demo's as well.

Using `new Date('2000-01-01')` shows `31 Dec 1999`, but saved value is initial correct value.
https://jsfiddle.net/of_6/kw2h4pom/1/
Also using this value breaks in Firefox and IE

Setting a date with time `new Date('2000-01-01T00:00:00')` shows correct date.

**Comment by jfmdev** [comment]
Hi Alex,

Thanks for using **ngComboDatePicker**. Indeed, this library depends of the [Date](http://www.w3schools.com/jsref/jsref_obj_date.asp) class in order to parse the strings passed in the `ng-date` attribute.

However, the _Date_ class belongs to the [JavaScript standard built-in objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects), so it's not possible to change how it parse the strings (since his implementation depends of each browser).

I'm unable to reproduce the error that you are describing, regarding `new Date('2000-01-01')`, in either Firefox, Chrome or IE, but, any way, this is an error related to the implementation of the _Date_ class, is not an error in the _ngComboDatePicker_ library.

**Comment by of6** [comment]
In your demo, the issue shows up for me. I'm on Chrome 48, OS X 10.11.12.

![screenshot](https://cloud.githubusercontent.com/assets/1820971/12712371/bc046bc0-c87c-11e5-9f1e-115b15a2455b.png)

**Comment by jfmdev** [comment]
Yes, that's the expected behaviour of the [Date](http://www.w3schools.com/jsref/jsref_obj_date.asp) class.

When writing dates in ISO 8601 syntax (`YYYY-MM-DD`), the dates are assumed to be in GMT time zone, however, if the client if located in another time-zone, the time is converted to the client's time zone.

In order to avoid that, you should specify the time-zone, as explained in [JavaScript Date Formats](http://www.w3schools.com/js/js_date_formats.asp)

**Comment by of6** [comment]
Oh ok, that makes sense, didn't even consider that. Super informative! Thanks for putting up with me! :baby:
