### ISSUE TITLE
Add an empty default value for each dropdown as the 1st option

### ISSUE THREAD

**Issue by armyofda12mnkeys** [jfmdev/ngComboDatePicker#4]
Hey @jfmdev,
When asking DOB in a Diabetes questionnaire pretend, you _could_ have a default value for a required DOB field question  ... 
but then old people submit the default DOB sometimes without thinking about changing the default. 

Is there a way to have an set of empty values for each dropdown to force the user to change the date (if i used ng-required/ng-messages for example on the datepicker)? 
Something customizable possibly so it could say: "--" / "--" / "--"
  or say: "--Please choose--" / "-Please choose--" / "-Please choose--".
  or sometimes ive seen empty values as the default in the dropdowns: "" / "" / ""
Maybe something like so to make it customizable:

```
<ng-combo-date-picker 
  ng-model="currentquestion.datemodel"
  ng-firstvaluedefault-month="--Please choose a month--"
  ng-firstvaluedefault-date="--Please choose a date--"
  ng-firstvaluedefault-year="--Please choose a year--" ... />
```

I'm guessing by default they would show up when associated with an initial empty/NULL/invalid model.
Is this possible to get into the plugin? 
I'm not sure I can add myself so thought I'd ask, but can look later to do this.

Thanks,
Ari

**Comment by jfmdev** [comment]
Hey Ari,

Thanks for your suggestion.

By default, the directive used to set the date to the current day, if the value in `ngModel` was `null`. However, I have made a new release that allow null values, in which case the combo boxes are empties.

So for example, if in the controller you initialize the model as `null`:

``` javascript
$scope.myDate = null;
```

Then the combo boxes are going to by empties and you can display a message when the variable is `null`:

``` html
<ng-combo-date-picker ng-model="myDate"></ng-combo-date-picker>
<span ng-show="myDate == null">You must select a date</span>
```

Also, after the user clicks the Submit button, you can verify if the variable is null, in order to avoid submitting the data.

Best regards

**Comment by armyofda12mnkeys** [comment]
Awesome, Thanks @jfmdev!
I'll let you know if I notice any more usability suggestions.
This is the best angular DOB/date dropdown project since its can support international standards/months
and many other features which makes it a pleasure to work with.

Thanks again,
Ari
