### ISSUE TITLE
When I select future date then it will automatically resets month dropdown.

### ISSUE THREAD

**Issue by Suresh-Lakum** [jfmdev/ngComboDatePicker#40]
So when I select any future date it automatically resets month drop-down.

**Comment by jfmdev** [comment]
What value are you passing to the `ng-max-date` parameter?

> Don't forget that, by default, the directive only lets you choose dates from the last 100 years till the present.

**Comment by Suresh-Lakum** [comment]
I am passing future date. E.g. from now 90 years in future.

**Comment by jfmdev** [comment]
Can you share your code (at least the part related to this library)?

**Comment by jfmdev** [comment]
Closed due to inactivity

**Comment by didnotwant** [comment]
@jfmdev — I’m sure that I encountered the same problem. As I understand, @Suresh-Lakum meant that when e.g. your max date is set to `11-23-2018`, the max year is of course set to `2018` which may cause a problem when one selects e.g. month `12`, day `2` and year `2018`. It’s possible to select such date and it results in unexpectedly cleared day or month field depending on which value is greater than the one of max date.

I was able to reproduce it on [the demo page](http://jfmdev.github.io/ngComboDatePicker/) in `Define minimum and maximum dates` section: in the second picker just select day `20` and change the year to `2016` to see that the day was cleared.

In general, I think the datepicker needs more complicated conditions on recalculating particular date parts.

A workaround for that might be setting 31 Dec of current year as a max date so that the user can’t select "wrong" date which breaks the UX.

Anyway, it’d be great to have it fixed. Are there any chances?

**Comment by jfmdev** [comment]
Hi @didnotwant 

Unfortunately, that's not a bug, **it's a feature**: the library removes any value from the combo boxes that might make the user to choose an invalid date.

> For example, if the maximum date is `2019-06-22` and the current selection is `2018-06-25`, and then you change the year to `2019`, then the day combo box will be cleared, since you can't select the day `25` for June in 2019 (you can only select till `22`).

If you don't want the combo boxes to be cleared, then you should set the maximum date as the last day of the year (e.g. `2019-12-31`), and then update your code to verify that the user don't selects a dates higher than your original maximum date.
